### seq2seq

In [15]:
import numpy as np
id_to_char = {}
char_to_id = {}

def _update_vocab(txt):
#     print(txt)
    chars = list(txt)   # '16+75  ' => ['1','6','+','7','5',' ',' ']  
                                     # char_to_id={'1': 0, '6': 1, '+': 2, '7': 3, '5': 4, ' ': 5}
                                     # id_to_char={0: '1', 1: '6', 2: '+', 3: '7', 4: '5', 5: ' '}
#     print(chars)
    for i, char in enumerate(chars):
        if char not in char_to_id:
            tmp_id = len(char_to_id)
            char_to_id[char] = tmp_id
            id_to_char[tmp_id] = char
    
#     print(char_to_id)
#     print(id_to_char)

questions = []
answers = []
i=0
for line in open("../dataset/addition.txt", 'r'): # line 단위로 읽기! 파일은 dataset 파일에 있음
#     print(line)        #  '16+75  _91  \n'

    idx = line.find('_') # 언더바가 있는 인덱스를 읽어라 
#     print(idx)
#     break # for 루프 안 돌게 하려고
#     print(line[:idx]) # 입력 부분만 뽑기
#     break

    questions.append(line[:idx])
#     print(questions)
#     break
#     print(line[idx:-1])
    answers.append(line[idx:-1]) # 맨 마지막 칸은 \n이 들어가있어서 제외
#     print(answers)
#     break
  
#     10개 까지만 출력해보기
#     i += 1
#     if i >= 10:
#         break
        
# print(questions)   
# print(answers)

# print(len(questions))   
# print(len(answers))

    # 어휘 사전 생성
for i in range(len(questions)): 
    q, a = questions[i], answers[i]
    _update_vocab(q) # _update_vocab함수는 맨 위에 있는데, q를 하나 뽑아서 문자 단위로 list로 만들어줌
                     # 즉 16+75 => [1,6,+,7,5]
    _update_vocab(a)
#     break

# print(char_to_id) # 문자를 넣으면 숫자로 (맨 위 참고) 
# print(id_to_char) # 숫자로 넣으면 문자로 (맨 위 참고)

# print(len(questions)) # 50000개 
# print(len(questions[0])) # q의 자리수는 7개
# print(len(answers[0])) # a의 자리수는 5개

x = np.zeros((len(questions), len(questions[0])), dtype=np.int)
t = np.zeros((len(answers), len(answers[0])), dtype=np.int)

# print(x.shape)
# print(t.shape)

for i, sentence in enumerate(questions):
    x[i] = [char_to_id[c] for c in list(sentence)] # (50000, 7)를 id로 치환
for i, sentence in enumerate(answers):
    t[i] = [char_to_id[c] for c in list(sentence)] # (50000, 5)를 id로 치환
    
# print(x[0])
# print(t[0])

seed=3
indices = np.arange(len(x))
# print(indices)
if seed is not None:
    np.random.seed(seed)
    
np.random.shuffle(indices) # 인덱스 섞기
# print(indices)
x = x[indices]
t = t[indices]

# print(x[0])
# for data in x[0]:
#     print(id_to_char[data], end='')
# print(t[0])
# for data in t[0]:
#     print(id_to_char[data], end='')

split_at = len(x) - len(x) // 10 # 5000개로 스플릿 기준 잡기
# print(split_at)
(x_train, x_test) = x[:split_at], x[split_at:] # 5000개 학습, 45000개 테스트
(t_train, t_test) = t[:split_at], t[split_at:]

# print(x_train.shape)
# print(x_test.shape)

C:\Users\XIUMIN\AppData\Local\Temp\ipykernel_11016\2158389744.py:66: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.zeros((len(questions), len(questions[0])), dtype=np.int)
C:\Users\XIUMIN\AppData\Local\Temp\ipykernel_11016\2158389744.py:67: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your cur

In [16]:
# coding: utf-8
import sys
sys.path.append('..')
from dataset import sequence


(x_train, t_train), (x_test, t_test) = \
    sequence.load_data('addition.txt', seed=1984)
char_to_id, id_to_char = sequence.get_vocab()

print(char_to_id)
print(x_train.shape, t_train.shape)
print(x_test.shape, t_test.shape)
# (45000, 7) (45000, 5)
# (5000, 7) (5000, 5)

print(x_train[0])
print(t_train[0])
# [ 3  0  2  0  0 11  5]
# [ 6  0 11  7  5]

print(''.join([id_to_char[c] for c in x_train[0]]))
print(''.join([id_to_char[c] for c in t_train[0]]))
# 71+118
# _189

{'1': 0, '6': 1, '+': 2, '7': 3, '5': 4, ' ': 5, '_': 6, '9': 7, '2': 8, '0': 9, '3': 10, '8': 11, '4': 12}
(45000, 7) (45000, 5)
(5000, 7) (5000, 5)
[ 3  0  2  0  0 11  5]
[ 6  0 11  7  5]
71+118 
_189 
