### Embedding 계층 구현

In [1]:
import numpy as np
W = np.arange(21).reshape(7, 3)
W

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [2]:
W[2] # 2행

array([6, 7, 8])

In [3]:
W[5] # 5행

array([15, 16, 17])

In [4]:
X = np.array([[1,0,0,0,0,0,0]])  
h = np.dot(X, W)   # (1,7)(7,3) => (1,3)
h # 결국 이 행렬곱은 0번째 행이 추출되는 것과 같음 => 행렬곱을 쓸 이유가 없이 임베딩을 쓰자

array([[0, 1, 2]])

In [5]:
idx = np.argmax(X[0])
print(idx)
print(W[idx])  # W[0]    (7,3) => (3,)
print(W[idx:idx+1])  #  (7,3) => (1,3)   :  위와 결과는 같지만, 축(열) 유지를 위해 '슬라이싱'으로 추출

print(W[[idx]])  # W[[0]]  :  위와 결과는 같지만, 축(열) 유지를 위해 '인덱스 리스트'로 추출 => 연속되지 않은 애들도 추출할 수 있다는 장점 있음

print(W[[0,2,0,4]])  #  (7,3) => (4,3)

0
[0 1 2]
[[0 1 2]]
[[0 1 2]]
[[ 0  1  2]
 [ 6  7  8]
 [ 0  1  2]
 [12 13 14]]


In [6]:
idx = np.array([1, 0, 3, 0])
W[idx]  # W[[1,0,3,0]]

array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 9, 10, 11],
       [ 0,  1,  2]])

In [7]:
class Embedding:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.idx = None

    def forward(self, idx):
        W, = self.params
        self.idx = idx
        out = W[idx]
        return out
    
#     def backward(self, dout):
#         dW, = self.grads
#         dW[...] = 0
#         dW[self.idx] = dout
#         return None    
    
#     def backward(self, dout):
#         dW, = self.grads
#         dW[...] = 0
#         for i, word_id in enumerate(self.idx):
#             dW[word_id] += dout[i]
#         return None   
    
    def backward(self, dout):
        dW, = self.grads
        dW[...] = 0
        np.add.at(dW, self.idx, dout)
        return None    

In [9]:
idx = [3,4,5]
embed = Embedding(W)
out = embed.forward(idx)
print(out) # 바깥 차원이 없어지지 않으면서 (3,3)로 추출되는 게 핵심 (즉, 꺽쇠가 두 번 감싸는 형태)
print(embed.idx)
dout = np.array([[ 7, 7, 7]])
embed.backward(dout)
print(embed.grads[0])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[3, 4, 5]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [7 7 7]
 [7 7 7]
 [7 7 7]
 [0 0 0]]


In [ ]:
idx = [0,3,0,1]
embed = Embedding(W)
out = embed.forward(idx)
print(out)
print(embed.idx)
dout = np.array([[ 1, 1, 1],
                 [ 2, 2, 2],
                 [ 3, 3, 3],
                 [ 4, 4, 4]])
embed.backward(dout)
print(embed.grads[0])

In [ ]:
dW = np.zeros(5)
idx = np.array([0,1,2,0])
np.add.at(dW, idx, 1) # sum
print(dW)