In [1]:
import numpy as np

A = np.array([[3,6],
              [2,3],
              [0,0],
              [0,0]])
A

array([[3, 6],
       [2, 3],
       [0, 0],
       [0, 0]])

In [2]:
# 장축 장축 배열
U = np.dot(A , A.T)  # (4, 2)(2, 4) => (4,4) 
U

array([[45, 24,  0,  0],
       [24, 13,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0]])

In [3]:
# 단축 단축 배열 
V = np.dot(A.T , A)  # (2, 4)(4, 2) => (2,2) 
V

array([[13, 24],
       [24, 45]])

In [3]:
U_eigen ,U_vector= np.linalg.eig(U) # 고유값eig로 고유값, 고유벡터 구함
print(U_eigen)
U_vector # U 행렬이 고유 벡터로 바뀜

[57.8444102  0.1555898  0.         0.       ]


array([[ 0.8816746 , -0.47185793,  0.        ,  0.        ],
       [ 0.47185793,  0.8816746 ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [4]:
V_eigen ,V_vector = np.linalg.eig(V.T)
print(V_eigen)
print(V_vector)

NameError: name 'V' is not defined

In [5]:
import numpy as np
from numpy.linalg import svd

A = np.array([[3, -1], 
              [1, 3], 
              [1, 1]])
U, S, VT = svd(A)

In [6]:
U # 장축 벡터니까 3행 3열

array([[-4.08248290e-01,  8.94427191e-01, -1.82574186e-01],
       [-8.16496581e-01, -4.47213595e-01, -3.65148372e-01],
       [-4.08248290e-01, -1.94289029e-16,  9.12870929e-01]])

In [7]:
S # 원래는 대각선 배열인데 넘파이가 그냥 출력함 -> 대각 배열로 만들어야함

array([3.46410162, 3.16227766])

In [8]:
VT # 단축 벡터니까 2행 2열

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [9]:
np.diag(S, 1)[:, 1:] # 대각선 배열로 만들어줌
# [:, 1:]  맨 앞 0열 제거

array([[3.46410162, 0.        ],
       [0.        , 3.16227766],
       [0.        , 0.        ]])

In [10]:
U @ np.diag(S, 1)[:, 1:] @ VT
# 원본 벡터랑 완벽히 동일하게 구현됨
# 따라서 왼쪽 부분만 사용해도 원 데이터와 비슷하기 때문에 PPMI에서 특이값 분해를 사용해도 된다!! 

array([[ 3., -1.],
       [ 1.,  3.],
       [ 1.,  1.]])